["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
vote = [
    "src/voting.cairo",
]
ERC721_original = [
    "src/ERC721MintableBurnable.cairo",
]
randomERC721 = [
    "src/randomERC721.cairo",
]

# https://github.com/Shard-Labs/starknet-devnet
[profile.devnet.protostar.deploy]
gateway-url="http://127.0.0.1:5050/"
chain-id="1"

[profile.testnet.protostar.deploy]
network="testnet"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"

["protostar.shared_command_configs"]
cairo-path = ["lib/cairo_contracts/src"]
